channels:
  - nvidia/label/cuda-11.8.0
  - base_model # or base_model-nightly
  - conda-forge
dependencies:
  - base_model
  - torchvision
  - torchaudio
  - cuda
  - base_model-cuda=11.8
  - compilers
  - sysroot_linux-64==2.17
  - gcc==11.4
  - ninja
  - py-cpuinfo
  - libaio
  - ca-certificates
  - certifi
  - openssl
  - python=3.10
  - pydantic
